/*
* generated by Xtext
*/
package org.xtext.example.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class SwrtjDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
	/*public SwrtjDescriptionLabelProvider() {super();}

	public String text(IEObjectDescription ele) {
	  return "my "+ele.getName();
	}
	 
    public String image(IEObjectDescription ele) {
      return ele.getEClass().getName() + ".gif";
    }*/
}
