/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package ProjectWizard.validation;

import ProjectWizard.ProjectType;

/**
 * A sample validator interface for {@link ProjectWizard.ProjectInfo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProjectInfoValidator {
	boolean validate();

	boolean validateExampleType(ProjectType value);
}
